export const ADD_TO_CHARS = 'ADD_TO_CHARS';
export const ADD_FILTERED_CHARS = 'ADD_FILTERED_CHARS';
export const CLEAR_FILTERED_CHARS = 'CLEAR_FILTERED_CHARS';
export const ADD_TO_CHARS_FAILTURE = 'ADD_TO_CHARS_FAILTURE';
